### ISSUE TITLE
Train Model does not take the time multiplier into account when determining if the train is over max speed

### ISSUE THREAD

**Issue by Mazztwo** [zoo1/ECE_1186_Trains#1]
Summary: When the train model determines if it is over max speed it should take into account the time multiplier and remove it from the calculation
System Configuration: Zach's Computer
Steps to reproduce: Set Power to 15 Watts, Set time multiplier to 1000
Expected Behavior: velocity exceeds the limit
Actual Behavior: velocity does not excede the limit

**Comment by zoo1** [comment]
fixed in commit 1082d504050f70482bfb43557a2bb92a128ffa91. Tested via steps to reproduce
